name: Revisit Solutions
favicon: null
layout_spectrum: 0.96791
typography_spectrum: 0.76808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e9fa3'
    - '#32b9aa'
    - '#19756a'
    - '#79ccc4'
  brandStrength: 0.30451236409135163
  lightness: 0.46209539426490664
  saturation: 0.7076410562731326
  rhythmicContrast: 0.5849971196148545
purpose: []
