name: Revisit Solutions
favicon: null
layout_spectrum: 0.30165084707550704
typography_spectrum: 0.9084077237639576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30451236409135163
  lightness: 0.46209539426490664
  saturation: 0.7076410562731326
  rhythmicContrast: 0.5849971196148545
purpose: []
